language: perl
perl:
- '5.18'
services:
- redis-server
install:
- cpanm Carton
- carton install
- carton bundle
- carton install --cached --deployment
script:
- carton exec ./scripts/lint.sh
- cd shorturl; carton exec perl script/shorturl test; cd ..;
before_install:
- openssl aes-256-cbc -K $encrypted_ba9823ddfcf4_key -iv $encrypted_ba9823ddfcf4_iv
  -in id_rsa.enc -out ./id_rsa -d
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 ./id_rsa # this key should have push access
  - ssh-add ./id_rsa
  - bash scripts/deploy.sh
